= School Timetabling (Java, Quarkus, AMQ, Maven)

The quickstart consists of two modules:

* Client runs the UI and sends requests to the Solver via AMQ.
* Solver optimizes the requests sent via AMQ and sends results back to AMQ broker.

[NOTE]
Starting the AMQ Artemis broker requires you to install https://docs.docker.com/compose/install/[docker-compose].

== Run the application with live coding

. Start the AMQ Artemis broker, the Solver Server and Client application with the `run.sh` script, which starts all 3 processes:
+
[source, shell]
----
$ ./run.sh
----
+

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

Then try _live coding_:

. Make some changes in the source code.
. Refresh your browser (F5).

Notice that those changes are immediately in effect.

== Package and run the application

When you're done iterating in `quarkus:dev` mode, run the application as a conventional jar file.
Before running any application, start the AMQ Artemis broker:

[source, shell]
----
$ docker-compose up
----

=== Package and run the Solver Server application

. Compile it with Maven:
+
[source, shell]
----
$ cd amq-quarkus-school-timetabling-solver
$ mvn package -DskipTests
----
+
. Run it:
+
[source, shell]
----
$ java -jar ./target/*-runner.jar -Dquarkus.http.port=8081
----

[NOTE]
Use the custom port to avoid conflict with the Client application.

=== Package and run the Client application

. Compile it with Maven:
+
[source, shell]
----
$ cd amq-quarkus-school-timetabling-client
$ mvn package -DskipTests
----
+
. Run it:
+
[source, shell]
----
$ java -jar ./target/*-runner.jar
----
+

. Visit http://localhost:8080 in your browser.

== Run a native executable

First, https://quarkus.io/guides/building-native-image#configuring-graalvm[install GraalVM and gu install the native-image tool]

=== Compile and run the Solver application natively

. Compile the Solver application natively:
+
[source, shell]
----
$ cd amq-quarkus-school-timetabling-solver
$ mvn package -Dnative -DskipTests -Dquarkus.profile=native
----
+
. Run the native executable:
+
[source, shell]
----
$ ./target/*-runner
----

=== Compile and run the Client application natively

. Compile the Client application natively:
+
[source, shell]
----
$ cd amq-quarkus-school-timetabling-client
$ mvn package -Dnative -DskipTests -Dquarkus.profile=native
----
+
[WARNING]
====
The `-Dquarkus.profile=native` is a temporary workaround for https://github.com/quarkusio/quarkus/issues/13341[an issue in Quarkus 1.10].
====

. Run a database. By default, `application.properties` is configured for H2:
.. Download the http://www.h2database.com/html/download.html[H2 database] (Platform-independent zip) and unzip it.
.. Start the H2 server with the option `-ifNotExists` (not recommended in production):
+
[source, shell]
----
$ cd h2/bin
$ java -cp h2*.jar org.h2.tools.Server -ifNotExists
----

. Run the native executable:
+
[source, shell]
----
$ ./target/*-runner
----

. Visit http://localhost:8080 in your browser.

== More information

Visit https://www.optaplanner.org/[www.optaplanner.org].
