# For a local development without any Kubernetes cluster.
version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
      POSTGRES_DB: school-timetabling

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    volumes:
      - .:/var/lib/artemis/etc-override
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin