= School Timetabling (OpenShift, Java, Quarkus, Maven)

This demo shows how to use the OptaPlanner Operator to run OptaPlanner workloads on OpenShift.

*Please note that the OptaPlanner Operator used in this demo is experimental. As such, it provides no guarantees
in terms of maturity and backward compatibility.*

== Get your environment running

Use an existing OpenShift cluster or download and start the https://developers.redhat.com/products/codeready-containers/overview[RedHat CodeReady Containers].

WARNING: Be sure to pick the _Red Hat OpenShift Local_, as the other option, the _Developer Sandbox for Red Hat OpenShift_ does not
allow installing new operators.

The CodeReady Containers need more resources to run this demo. Before starting the local cluster, increase the available memory
to 16 384 MiB by running `crc config set memory 16384`.

Install the https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI (`oc`)].

Login as a user with the `cluster-admin` role.

[#deployOperator]
== Deploy the OptaPlanner operator

. create a new OpenShift project called _demo_ by running `oc new-project demo`
. please follow the https://github.com/kiegroup/optaplanner/blob/main/optaplanner-operator/README.adoc#deployToOpenShift[optaplanner-operator README]

== Deploy the demo app

. change directory to `optaplanner-quickstarts/technology/kubernetes`
. build the maven project via `mvn clean install`
. change directory to `demo-app`
. make sure the current OpenShift project is `demo`: `oc project demo`
. deploy the demo-app via a maven command: `mvn clean package -Dopenshift -Dquarkus.openshift.namespace=demo -Dquarkus.openshift.env.vars.kafka-bootstrap-servers=<kafka bootstrap servers address>`

To find the address of the Kafka bootstrap servers:

. login to the OpenShift UI console
. open the _openshift-operators_ project and navigate to _Networking -> Services_
. open the _<kafka-cluster-name>-kafka-bootstrap_ service and notice its hostname and service port mapping for TCP clients under the _Service routing_ section
. the address is a compound of the `<hostname>:<service port>`

TIP: If you encounter the `Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed` exception due to self-signed certificate during the build, add the `-Dquarkus.kubernetes-client.trust-certs=true` property.

== Create the school-timetabling solver

[#buildSolverImage]
=== Build and push the school-timetabling container image

Build and push the school-timetabling container image to a registry of your choice:

. change directory to `school-timetabling`
. run `mvn clean package -Dopenshift -Dquarkus.container-image.group=<image group> -Dquarkus.container-image.registry=<container registry>
 -Dquarkus.container-image.username=<container registry username> -Dquarkus.container-image.password=<container registry password>`

Where the container registry is a repository used to store and access container images (e.g. docker.io) and the image
group is an organization or a personal account in that registry.

[TIP]
.Pushing an image to a container image registry
====
You can use https://quay.io[quay.io] as a container image registry.

. open https://quay.io in the browser and login with your Red Hat account
. create a new repository called _school-timetabling_, switch its visibility to _Public_ and click the _Create Public Repository_ button
. the image is identified by quay.io/<login>/<image name>:<tag>
====

=== Create the Solver custom resource

The Solver custom resource describes the problem to solve on OpenShift and the infrastructure it requires.
Below are the mandatory spec properties:

- `kafkaCluster` - the name of the Kafka cluster created during the <<#deployOperator, Strimzi installation>>
- `kafkaBootstrapServers` - the kafka bootstrap servers address
- `solverImage` - the school-timetabling container image <<#buildSolverImage, built and pushed>> to a registry of your choice

An example of the `Solver` custom resource looks like follows:

[source yaml]
----
apiVersion: org.optaplanner.solver/v1
kind: Solver
metadata:
  name: school-timetabling
spec:
  kafkaCluster: my-cluster
  kafkaBootstrapServers: my-cluster-kafka-bootstrap.openshift-operators.svc.cluster.local:9092
  solverImage: quay.io/example/school-timetabling:latest
  scaling:
    replicas: 1
----

Create the `Solver` resource via `oc apply -f <file>`.

== Run the demo-app

. find out the demo-app address by running `oc get route`; see the _HOST/PORT_ column of its output
. open the address in the browser
. change the number of lessons, if needed, and click the _Create & send_ button

== Local development

To work locally on this demo without OpenShift or any Kubernetes cluster:

. start the PostgreSQL database and a Kafka broker by running `docker-compose up`
. run the `demo-app` by `mvn quarkus:dev` in the `demo-app` directory
. run the `school-timetabling` by `mvn quarkus:dev` in the `school-timetabling` directory