@Library('jenkins-pipeline-shared-libraries')_

pr_check_script = null

pipeline {
    agent {
        label 'ubuntu'
    }
    options {
        timestamps()
        timeout(time: 720, unit: 'MINUTES')
        disableConcurrentBuilds(abortPrevious: true)
    }
    environment {
        BUILDCHAIN_PROJECT = 'apache/incubator-kie-optaplanner-quickstarts'
        BUILDCHAIN_CONFIG_REPO = 'apache/incubator-kie-optaplanner'
        BUILDCHAIN_CONFIG_FILE_PATH = '.ci/buildchain-config.yaml'

        OPTAPLANNER_BUILD_MVN_OPTS_UPSTREAM = '-Dfull'
        BUILD_MVN_OPTS_CURRENT = '-Dfull'
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    // load `pr_check.groovy` file from kogito-pipelines:main
                    dir('kogito-pipelines') {
                        checkout(githubscm.resolveRepository('incubator-kie-kogito-pipelines', 'apache', 'main', false, 'kie-ci')) // TODO to change back to kiegroup:main
                        pr_check_script = load 'dsl/scripts/pr_check.groovy'
                    }
                }
            }
        }
        stage('PR check') {
            steps {
                script {
                    dir('kogito-pipelines') {
                        pr_check_script.launch()
                    }
                }
            }
        }
    }
}